### ISSUE TITLE
Api's not working.

### ISSUE THREAD

**Issue by pankajnegi1893** [JincorTech/frontend-moon-wallet#74]
https://api.moonwallet.tech API not working.

**Comment by hlogeon** [comment]
Yeah, the domain name is expired and we don't see any reason to pay for it now and in the future. You can run backend locally https://github.com/secret-tech/backend-token-wallets

**Comment by pankajnegi1893** [comment]
thanks for reply @hlogeon. Yes, I have checked this backend project. I have followed the instruction which is mention in the README file. But I am getting Error when Running the Project.

Node version:- v10.15.3
NPM version:- 6.4.1

I have run these Command:- 
1)  docker-compose -f docker-compose.test.yml build --no-cache
2)  docker-compose -f docker-compose.test.yml run API /bin/sh
3) npm i
4) npm run start:test

But when I am Running npm run start:test. Getting the following error:-

[nodemon] watching: /Volumes/Data/pankajReactNative/2019/June/backend-token-wallets-develop/src/**/*
[nodemon] starting `mocha -r ts-node/register -r test/prepare.ts src/**/*.spec.ts`
(node:6170) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:6170) UnhandledPromiseRejectionWarning: MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Volumes/Data/pankajReactNative/2019/June/backend-token-wallets-develop/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:189:13)
    at Connection.<anonymous> (/Volumes/Data/pankajReactNative/2019/June/backend-token-wallets-develop/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:277:13)
    at Connection.emit (events.js:189:13)
    at Socket.<anonymous> (/Volumes/Data/pankajReactNative/2019/June/backend-token-wallets-develop/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:6170) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6170) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

can you help me regarding this?
